
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjihdpkqwxyutplkbudh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqaWhkcGtxd3h5dXRwbGtidWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTQzMzQsImV4cCI6MjA2MDI5MDMzNH0.bVmDyVeidbr-nfS4D2XcB3xNIuXl7ZjycLd8-aQDRQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the standard typed client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create a raw client without type checking for custom tables
export const supabaseCustom = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
