// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnjmjhhxekimqxueyqzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuam1qaGh4ZWtpbXF4dWV5cXp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MDQyNTIsImV4cCI6MjA1NTE4MDI1Mn0.47no5sOG4UHwyIymZDdVoS3Yc27wSQItLoF70POCSHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);